version: "3.1"
services:
  mongo-setup:
    image: mongo:4.2.7
    container_name: mongo-setup
    restart: on-failure
    networks:
      default:
    volumes:
      - ./scripts:/scripts:rx
    entrypoint: [ "/scripts/setup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3
  
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.2.7
    expose:
      - 30001
    ports:
      - 30001:30001
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "30001", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ${VOLUME_DIR}/mongo/data1/db:/data/db
      - ${VOLUME_DIR}/mongo/data1/configdb:/data/configdb
  
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.2.7
    expose:
      - 30002
    ports:
      - 30002:30002
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "30002", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ${VOLUME_DIR}/mongo/data2/db:/data/db
      - ${VOLUME_DIR}/mongo/data2/configdb:/data/configdb
  
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.2.7
    expose:
      - 30003
    ports:
      - 30003:30003
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "30003", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ${VOLUME_DIR}/mongo/data3/db:/data/db
      - ${VOLUME_DIR}/mongo/data3/configdb:/data/configdb